name: Main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  mac-build:
    runs-on: macos-latest

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Qt
        run: brew update && brew install qt@5

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0

      - run: echo "basename=bsnes-plus-${{env.GITHUB_REF_SLUG}}-mac" >> $GITHUB_ENV
        name: Set variables

      - run: |
          cd bsnes
          make qtpath=/usr/local/opt/qt@5

      # cross-platform tar.gz creator:
      - name: Create ${{env.basename}}.tar.gz
        run: >
          go run
          .github/scripts/tar.go
          -z
          -o ${{env.basename}}.tar.gz
          bsnes+.app/

      - uses: actions/upload-artifact@v1
        name: Upload artifact
        with:
          name: ${{env.basename}}.tar.gz
          path: ${{github.workspace}}/${{env.basename}}.tar.gz

  windows-build:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        name: Install MSYS2
        with:
          update: true
          install: >-
            base-devel
            git
            coreutils
            make
            mingw-w64-x86_64-toolchain
            p7zip

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set variables
        run: |
          echo "basename=bsnes-plus-${{env.GITHUB_REF_SLUG}}-windows" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build bsnes
        shell: msys2 {0}
        run: |
          cd bsnes
          rm out/.gitignore

          mingw32-make -j2 build platform=win profile=performance version=${{env.GITHUB_REF_SLUG}}
          mingw32-make -j2 build platform=win profile=accuracy version=${{env.GITHUB_REF_SLUG}}
          mingw32-make -j2 platform=win version=${{env.GITHUB_REF_SLUG}}

          cd out
          mv ../../snesfilter/snesfilter.dll .
          mv ../../snesreader/snesreader.dll .
          mv ../../snesmusic/snesmusic.dll .
          mv ../../supergameboy/supergameboy.dll .

          mkdir bsxdat
          cp -ra ../data/bsxdat bsxdat

          cp ../../external/qt/mingw-w64/bin/*.dll .
          cp -ra ../../external/qt/mingw-w64/plugins/* .

          cp "$MINGW_PREFIX/bin/libgcc_s_seh-1.dll" .
          cp "$MINGW_PREFIX/bin/libgomp-1.dll" .
          cp "$MINGW_PREFIX/bin/libstdc++-6.dll" .
          cp "$MINGW_PREFIX/bin/libwinpthread-1.dll" .

      - name: Create ${{env.basename}}.zip
        shell: msys2 {0}
        run: |
          cd bsnes
          mv out ${{env.basename}}
          7z a -r -mx=9 ../${{env.basename}}.zip ${{env.basename}}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.basename}}.zip
          path: ${{github.workspace}}\${{env.basename}}.zip
